[package]
name = "baler-cli"
version.workspace = true
edition.workspace = true
description = "A 'Cargo'-style package manager for `{box}` modules"
default-run = "baler"

[lib]
name = "baler_cli"
path = "src/lib.rs"

[[bin]]
name = "baler"
path = "src/bin/baler.rs"

[dependencies]
baler-core = { path = "../baler-core", features = ["network"] }
baler-native = { path = "../native-code-handler" }
anyhow.workspace = true
clap.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
